<a href="https://colab.research.google.com/github/Gouthamraju13/2303A51L16-AIML-27/blob/main/2303A51L16_week_2_assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from collections import deque

def bfs(graph, start_vertex):
    visited = set()
    queue = deque([start_vertex])

    while queue:
        current_vertex = queue.popleft()
        if current_vertex not in visited:
            print(current_vertex, end=' ')
            visited.add(current_vertex)


            queue.extend(neighbor for neighbor in graph[current_vertex] if neighbor not in visited)


graph = {
    0: [1, 3],
    1: [0, 2, 3],
    2: [1, 4, 5],
    3: [0, 1, 4],
    4: [2, 3, 5],
    5: [2, 4],
}

start_vertex = 0
print("BFS traversal starting from vertex", start_vertex, ":")
bfs(graph, start_vertex)

BFS traversal starting from vertex 0 :
0 1 3 2 4 5 

In [ ]:
def dfs(graph, start):
    visited = set()
    stack = [start]

    while stack:
        current_node = stack.pop()

        if current_node not in visited:
            print(current_node, end=' ')
            visited.add(current_node)

            # Push neighboring nodes onto the stack in reverse order to maintain desired order
            stack.extend(neighbor for neighbor in reversed(graph[current_node]) if neighbor not in visited)

# Example graph represented as an adjacency list
graph = {
    'A': ['B', 'S'],
    'B': ['A'],
    'C': ['D', 'E', 'F','S'],
    'D': ['C'],
    'E': ['H', 'C'],
    'F': ['C','G'],
    'G': ['S','H','F'],
    'H': ['G','E'],
    'S': ['A','C','G'],
}

start_node = 'A'
print("DFS traversal starting from node", start_node)
dfs(graph, start_node)

DFS traversal starting from node A
A B S C D E H G F 

In [ ]:
import numpy as np
from queue import PriorityQueue

class Node:
    def __init__(self, state, parent=None, action=None, cost=0, heuristic=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.cost = cost
        self.heuristic = heuristic

    def __lt__(self, other):
        return (self.cost + self.heuristic) < (other.cost + other.heuristic)

def h(state, goal_state):
    # Heuristic function for the 8-puzzle problem
    # Manhattan distance heuristic
    distance = 0
    for i in range(3):
        for j in range(3):
            value = state[i, j]
            if value != 0:
                goal_position = np.argwhere(goal_state == value)[0]
                distance += abs(i - goal_position[0]) + abs(j - goal_position[1])
    return distance

def a_star(initial_state, goal_state):
    open_set = PriorityQueue()
    closed_set = set()

    start_node = Node(initial_state)
    start_node.heuristic = h(initial_state, goal_state)
    open_set.put(start_node)

    while not open_set.empty():
        current_node = open_set.get()

        if np.array_equal(current_node.state, goal_state):
            path = []
            while current_node:
                path.append((current_node.action, current_node.state))
                current_node = current_node.parent
            return path[::-1]

        closed_set.add(tuple(current_node.state.flatten()))

        neighbors = get_neighbors(current_node.state)
        for action, neighbor_state in neighbors:
            if tuple(neighbor_state.flatten()) not in closed_set:
                new_cost = current_node.cost + 1
                new_node = Node(neighbor_state, current_node, action, new_cost, h(neighbor_state, goal_state))
                open_set.put(new_node)

    return None  # No solution found

def get_neighbors(state):
    neighbors = []
    zero_position = np.argwhere(state == 0)[0]

    for action in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
        new_position = zero_position + action

        if 0 <= new_position[0] < 3 and 0 <= new_position[1] < 3:
            neighbor_state = state.copy()
            neighbor_state[zero_position[0], zero_position[1]] = state[new_position[0], new_position[1]]
            neighbor_state[new_position[0], new_position[1]] = 0
            neighbors.append((action, neighbor_state))

    return neighbors

# Example usage:
initial_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
goal_state = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

solution = a_star(initial_state, goal_state)

if solution:
    for step, state in solution:
        print(f"Step {step}:")
        print(state)
        print("------")
else:
    print("No solution found.")


Step None:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
------
Step (-1, 0):
[[1 2 3]
 [4 5 0]
 [7 8 6]]
------
Step (0, -1):
[[1 2 3]
 [4 0 5]
 [7 8 6]]
------
Step (0, -1):
[[1 2 3]
 [0 4 5]
 [7 8 6]]
------
Step (1, 0):
[[1 2 3]
 [7 4 5]
 [0 8 6]]
------
Step (0, 1):
[[1 2 3]
 [7 4 5]
 [8 0 6]]
------
Step (0, 1):
[[1 2 3]
 [7 4 5]
 [8 6 0]]
------
Step (-1, 0):
[[1 2 3]
 [7 4 0]
 [8 6 5]]
------
Step (-1, 0):
[[1 2 0]
 [7 4 3]
 [8 6 5]]
------
Step (0, -1):
[[1 0 2]
 [7 4 3]
 [8 6 5]]
------
Step (1, 0):
[[1 4 2]
 [7 0 3]
 [8 6 5]]
------
Step (1, 0):
[[1 4 2]
 [7 6 3]
 [8 0 5]]
------
Step (0, -1):
[[1 4 2]
 [7 6 3]
 [0 8 5]]
------
Step (-1, 0):
[[1 4 2]
 [0 6 3]
 [7 8 5]]
------
Step (0, 1):
[[1 4 2]
 [6 0 3]
 [7 8 5]]
------
Step (0, 1):
[[1 4 2]
 [6 3 0]
 [7 8 5]]
------
Step (1, 0):
[[1 4 2]
 [6 3 5]
 [7 8 0]]
------
Step (0, -1):
[[1 4 2]
 [6 3 5]
 [7 0 8]]
------
Step (0, -1):
[[1 4 2]
 [6 3 5]
 [0 7 8]]
------
Step (-1, 0):
[[1 4 2]
 [0 3 5]
 [6 7 8]]
------
Step (0, 1):
[[1 4 2]
 [3 0 5]
